### PR TITLE
Add cleartext password below hash

### PR DESCRIPTION
**Pull request by TobleMiner**
Seems to be the lantiq SDK default

### CODE REVIEW

**Comment by elig0n** [comment]
@TobleMiner Are you sure the password is "admin" ? Hashcat gave me "amazon" for the same hash

**Comment by TobleMiner** [comment]
Possible. Had both in the same hashcat file, might have mixed them up

**Comment by systemcrash** [comment]
Please check. This is, after all, a pass-phrase.

**Comment by TobleMiner** [comment]
Yeah, it is amazon

**Pull request merged**
